-- Must be run with admin privilages (SYSTEM account)

--1) create db schema
CREATE USER chem_lab IDENTIFIED BY chem_lab;

--2) grant permissions
GRANT
CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, -
CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, -
CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, - 
CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE -
TO chem_lab;
